namespace DevExpress.UITemplates.Collection.UserControls {
    partial class EmployeeDetailsSimple {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            this.dataLayout = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.FirstNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.employeeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.LastNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.PrefixImageComboBoxEdit = new DevExpress.XtraEditors.ImageComboBoxEdit();
            this.DepartmentImageComboBoxEdit = new DevExpress.XtraEditors.ImageComboBoxEdit();
            this.StatusImageComboBoxEdit = new DevExpress.XtraEditors.ImageComboBoxEdit();
            this.HomePhoneTextEdit = new DevExpress.XtraEditors.ButtonEdit();
            this.MobilePhoneTextEdit = new DevExpress.XtraEditors.ButtonEdit();
            this.EmailTextEdit = new DevExpress.XtraEditors.ButtonEdit();
            this.PhotoPictureEdit = new DevExpress.XtraEditors.PictureEdit();
            this.AddressTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.CityTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.StateImageComboBoxEdit = new DevExpress.XtraEditors.ImageComboBoxEdit();
            this.ZipCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.FullNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.HireDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            this.BirthDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            this.TitleTextEdit = new DevExpress.XtraEditors.TextEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.ItemForFirstName = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForLastName = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForHomePhone = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForMobilePhone = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForEmail = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForPhoto = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.ItemForAddress = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForCity = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem2 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.ItemForFullName = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForBirthDate = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForState = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForZipCode = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem5 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.ItemForDepartment = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForHireDate = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem4 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.ItemForTitle = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForPrefix = new DevExpress.XtraLayout.LayoutControlItem();
            this.ItemForStatus = new DevExpress.XtraLayout.LayoutControlItem();
            this.barManager = new DevExpress.XtraBars.BarManager(this.components);
            this.actionsBar = new DevExpress.XtraBars.Bar();
            this.bbiSave = new DevExpress.XtraBars.BarButtonItem();
            this.bbiClearEditors = new DevExpress.XtraBars.BarButtonItem();
            this.bbiResetChanges = new DevExpress.XtraBars.BarButtonItem();
            this.barDockControlTop = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlBottom = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlLeft = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            this.actionImages = new DevExpress.Utils.SvgImageCollection(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayout)).BeginInit();
            this.dataLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.FirstNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PrefixImageComboBoxEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DepartmentImageComboBoxEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.StatusImageComboBoxEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HomePhoneTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.MobilePhoneTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.EmailTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PhotoPictureEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AddressTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CityTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.StateImageComboBoxEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ZipCodeTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.FullNameTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HireDateDateEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.HireDateDateEdit.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TitleTextEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFirstName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForLastName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForHomePhone)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForMobilePhone)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForEmail)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForPhoto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCity)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFullName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForBirthDate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForState)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForZipCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForDepartment)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForHireDate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForTitle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForPrefix)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForStatus)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.actionImages)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayout
            // 
            this.dataLayout.AllowCustomization = false;
            this.dataLayout.AllowGeneratingCollectionProperties = DevExpress.Utils.DefaultBoolean.True;
            this.dataLayout.AllowGeneratingNestedGroups = DevExpress.Utils.DefaultBoolean.True;
            this.dataLayout.Controls.Add(this.FirstNameTextEdit);
            this.dataLayout.Controls.Add(this.LastNameTextEdit);
            this.dataLayout.Controls.Add(this.PrefixImageComboBoxEdit);
            this.dataLayout.Controls.Add(this.DepartmentImageComboBoxEdit);
            this.dataLayout.Controls.Add(this.StatusImageComboBoxEdit);
            this.dataLayout.Controls.Add(this.HomePhoneTextEdit);
            this.dataLayout.Controls.Add(this.MobilePhoneTextEdit);
            this.dataLayout.Controls.Add(this.EmailTextEdit);
            this.dataLayout.Controls.Add(this.PhotoPictureEdit);
            this.dataLayout.Controls.Add(this.AddressTextEdit);
            this.dataLayout.Controls.Add(this.CityTextEdit);
            this.dataLayout.Controls.Add(this.StateImageComboBoxEdit);
            this.dataLayout.Controls.Add(this.ZipCodeTextEdit);
            this.dataLayout.Controls.Add(this.FullNameTextEdit);
            this.dataLayout.Controls.Add(this.HireDateDateEdit);
            this.dataLayout.Controls.Add(this.BirthDateDateEdit);
            this.dataLayout.Controls.Add(this.TitleTextEdit);
            this.dataLayout.DataSource = this.employeeBindingSource;
            this.dataLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayout.Location = new System.Drawing.Point(0, 24);
            this.dataLayout.Name = "dataLayout";
            this.dataLayout.OptionsView.UseParentAutoScaleFactor = true;
            this.dataLayout.Root = this.layoutControlGroup1;
            this.dataLayout.Size = new System.Drawing.Size(500, 396);
            this.dataLayout.TabIndex = 0;
            // 
            // FirstNameTextEdit
            // 
            this.FirstNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "FirstName", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.FirstNameTextEdit.EnterMoveNextControl = true;
            this.FirstNameTextEdit.Location = new System.Drawing.Point(75, 6);
            this.FirstNameTextEdit.Name = "FirstNameTextEdit";
            this.FirstNameTextEdit.Properties.ValidateOnEnterKey = true;
            this.FirstNameTextEdit.Size = new System.Drawing.Size(272, 20);
            this.FirstNameTextEdit.StyleController = this.dataLayout;
            this.FirstNameTextEdit.TabIndex = 8;
            // 
            // employeeBindingSource
            // 
            this.employeeBindingSource.DataSource = typeof(DevExpress.UITemplates.Collection.Models.Employee);
            // 
            // LastNameTextEdit
            // 
            this.LastNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "LastName", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.LastNameTextEdit.EnterMoveNextControl = true;
            this.LastNameTextEdit.Location = new System.Drawing.Point(75, 28);
            this.LastNameTextEdit.Name = "LastNameTextEdit";
            this.LastNameTextEdit.Properties.ValidateOnEnterKey = true;
            this.LastNameTextEdit.Size = new System.Drawing.Size(272, 20);
            this.LastNameTextEdit.StyleController = this.dataLayout;
            this.LastNameTextEdit.TabIndex = 9;
            // 
            // PrefixImageComboBoxEdit
            // 
            this.PrefixImageComboBoxEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Prefix", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PrefixImageComboBoxEdit.EnterMoveNextControl = true;
            this.PrefixImageComboBoxEdit.Location = new System.Drawing.Point(415, 267);
            this.PrefixImageComboBoxEdit.Name = "PrefixImageComboBoxEdit";
            this.PrefixImageComboBoxEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.PrefixImageComboBoxEdit.Size = new System.Drawing.Size(78, 20);
            this.PrefixImageComboBoxEdit.StyleController = this.dataLayout;
            this.PrefixImageComboBoxEdit.TabIndex = 11;
            // 
            // DepartmentImageComboBoxEdit
            // 
            this.DepartmentImageComboBoxEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Department", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.DepartmentImageComboBoxEdit.EnterMoveNextControl = true;
            this.DepartmentImageComboBoxEdit.Location = new System.Drawing.Point(75, 290);
            this.DepartmentImageComboBoxEdit.Name = "DepartmentImageComboBoxEdit";
            this.DepartmentImageComboBoxEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.DepartmentImageComboBoxEdit.Size = new System.Drawing.Size(419, 20);
            this.DepartmentImageComboBoxEdit.StyleController = this.dataLayout;
            this.DepartmentImageComboBoxEdit.TabIndex = 4;
            // 
            // StatusImageComboBoxEdit
            // 
            this.StatusImageComboBoxEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Status", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.StatusImageComboBoxEdit.EnterMoveNextControl = true;
            this.StatusImageComboBoxEdit.Location = new System.Drawing.Point(415, 313);
            this.StatusImageComboBoxEdit.Name = "StatusImageComboBoxEdit";
            this.StatusImageComboBoxEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.StatusImageComboBoxEdit.Size = new System.Drawing.Size(78, 20);
            this.StatusImageComboBoxEdit.StyleController = this.dataLayout;
            this.StatusImageComboBoxEdit.TabIndex = 6;
            // 
            // HomePhoneTextEdit
            // 
            this.HomePhoneTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "HomePhone", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.HomePhoneTextEdit.EnterMoveNextControl = true;
            this.HomePhoneTextEdit.Location = new System.Drawing.Point(75, 180);
            this.HomePhoneTextEdit.Name = "HomePhoneTextEdit";
            this.HomePhoneTextEdit.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.RegExpMaskManager));
            this.HomePhoneTextEdit.Properties.MaskSettings.Set("mask", "(\\(\\d\\d\\d\\) )?\\d{1,3}-\\d\\d-\\d\\d");
            this.HomePhoneTextEdit.Properties.UseMaskAsDisplayFormat = true;
            this.HomePhoneTextEdit.Properties.ValidateOnEnterKey = true;
            this.HomePhoneTextEdit.Size = new System.Drawing.Size(419, 20);
            this.HomePhoneTextEdit.StyleController = this.dataLayout;
            this.HomePhoneTextEdit.TabIndex = 12;
            // 
            // MobilePhoneTextEdit
            // 
            this.MobilePhoneTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "MobilePhone", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.MobilePhoneTextEdit.EnterMoveNextControl = true;
            this.MobilePhoneTextEdit.Location = new System.Drawing.Point(75, 202);
            this.MobilePhoneTextEdit.Name = "MobilePhoneTextEdit";
            this.MobilePhoneTextEdit.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.RegExpMaskManager));
            this.MobilePhoneTextEdit.Properties.MaskSettings.Set("mask", "(\\(\\d\\d\\d\\) )?\\d{1,3}-\\d\\d-\\d\\d");
            this.MobilePhoneTextEdit.Properties.UseMaskAsDisplayFormat = true;
            this.MobilePhoneTextEdit.Properties.ValidateOnEnterKey = true;
            this.MobilePhoneTextEdit.Size = new System.Drawing.Size(419, 20);
            this.MobilePhoneTextEdit.StyleController = this.dataLayout;
            this.MobilePhoneTextEdit.TabIndex = 13;
            // 
            // EmailTextEdit
            // 
            this.EmailTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Email", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.EmailTextEdit.EnterMoveNextControl = true;
            this.EmailTextEdit.Location = new System.Drawing.Point(75, 224);
            this.EmailTextEdit.Name = "EmailTextEdit";
            this.EmailTextEdit.Properties.ValidateOnEnterKey = true;
            this.EmailTextEdit.Size = new System.Drawing.Size(419, 20);
            this.EmailTextEdit.StyleController = this.dataLayout;
            this.EmailTextEdit.TabIndex = 14;
            // 
            // PhotoPictureEdit
            // 
            this.PhotoPictureEdit.Cursor = System.Windows.Forms.Cursors.Default;
            this.PhotoPictureEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Photo", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.PhotoPictureEdit.Location = new System.Drawing.Point(368, 7);
            this.PhotoPictureEdit.Name = "PhotoPictureEdit";
            this.PhotoPictureEdit.Properties.PictureStoreMode = DevExpress.XtraEditors.Controls.PictureStoreMode.ByteArray;
            this.PhotoPictureEdit.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Zoom;
            this.PhotoPictureEdit.Size = new System.Drawing.Size(125, 84);
            this.PhotoPictureEdit.StyleController = this.dataLayout;
            this.PhotoPictureEdit.TabIndex = 17;
            // 
            // AddressTextEdit
            // 
            this.AddressTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Address.Line", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.AddressTextEdit.EnterMoveNextControl = true;
            this.AddressTextEdit.Location = new System.Drawing.Point(75, 114);
            this.AddressTextEdit.Name = "AddressTextEdit";
            this.AddressTextEdit.Size = new System.Drawing.Size(419, 20);
            this.AddressTextEdit.StyleController = this.dataLayout;
            this.AddressTextEdit.TabIndex = 19;
            // 
            // CityTextEdit
            // 
            this.CityTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Address.City", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.CityTextEdit.EnterMoveNextControl = true;
            this.CityTextEdit.Location = new System.Drawing.Point(75, 136);
            this.CityTextEdit.Name = "CityTextEdit";
            this.CityTextEdit.Size = new System.Drawing.Size(124, 20);
            this.CityTextEdit.StyleController = this.dataLayout;
            this.CityTextEdit.TabIndex = 20;
            // 
            // StateImageComboBoxEdit
            // 
            this.StateImageComboBoxEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Address.State", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.StateImageComboBoxEdit.EnterMoveNextControl = true;
            this.StateImageComboBoxEdit.Location = new System.Drawing.Point(251, 137);
            this.StateImageComboBoxEdit.Name = "StateImageComboBoxEdit";
            this.StateImageComboBoxEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.StateImageComboBoxEdit.Properties.DropDownRows = 14;
            this.StateImageComboBoxEdit.Properties.Sorted = true;
            this.StateImageComboBoxEdit.Size = new System.Drawing.Size(95, 20);
            this.StateImageComboBoxEdit.StyleController = this.dataLayout;
            this.StateImageComboBoxEdit.TabIndex = 21;
            // 
            // ZipCodeTextEdit
            // 
            this.ZipCodeTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Address.ZipCode", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.ZipCodeTextEdit.EnterMoveNextControl = true;
            this.ZipCodeTextEdit.Location = new System.Drawing.Point(415, 137);
            this.ZipCodeTextEdit.Name = "ZipCodeTextEdit";
            this.ZipCodeTextEdit.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.RegExpMaskManager));
            this.ZipCodeTextEdit.Properties.MaskSettings.Set("mask", "\\d\\d\\d\\d\\d");
            this.ZipCodeTextEdit.Properties.UseMaskAsDisplayFormat = true;
            this.ZipCodeTextEdit.Size = new System.Drawing.Size(78, 20);
            this.ZipCodeTextEdit.StyleController = this.dataLayout;
            this.ZipCodeTextEdit.TabIndex = 22;
            // 
            // FullNameTextEdit
            // 
            this.FullNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "FullName", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.FullNameTextEdit.Location = new System.Drawing.Point(75, 50);
            this.FullNameTextEdit.Name = "FullNameTextEdit";
            this.FullNameTextEdit.Properties.ReadOnly = true;
            this.FullNameTextEdit.Size = new System.Drawing.Size(272, 20);
            this.FullNameTextEdit.StyleController = this.dataLayout;
            this.FullNameTextEdit.TabIndex = 23;
            // 
            // HireDateDateEdit
            // 
            this.HireDateDateEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "HireDate", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.HireDateDateEdit.EditValue = null;
            this.HireDateDateEdit.EnterMoveNextControl = true;
            this.HireDateDateEdit.Location = new System.Drawing.Point(75, 312);
            this.HireDateDateEdit.Name = "HireDateDateEdit";
            this.HireDateDateEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.HireDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.HireDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.HireDateDateEdit.Size = new System.Drawing.Size(272, 20);
            this.HireDateDateEdit.StyleController = this.dataLayout;
            this.HireDateDateEdit.TabIndex = 7;
            // 
            // BirthDateDateEdit
            // 
            this.BirthDateDateEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "BirthDate", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.BirthDateDateEdit.EditValue = null;
            this.BirthDateDateEdit.EnterMoveNextControl = true;
            this.BirthDateDateEdit.Location = new System.Drawing.Point(75, 72);
            this.BirthDateDateEdit.Name = "BirthDateDateEdit";
            this.BirthDateDateEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.BirthDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.BirthDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.BirthDateDateEdit.Size = new System.Drawing.Size(272, 20);
            this.BirthDateDateEdit.StyleController = this.dataLayout;
            this.BirthDateDateEdit.TabIndex = 16;
            // 
            // TitleTextEdit
            // 
            this.TitleTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.employeeBindingSource, "Title", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this.TitleTextEdit.EnterMoveNextControl = true;
            this.TitleTextEdit.Location = new System.Drawing.Point(75, 266);
            this.TitleTextEdit.Name = "TitleTextEdit";
            this.TitleTextEdit.Properties.ValidateOnEnterKey = true;
            this.TitleTextEdit.Size = new System.Drawing.Size(272, 20);
            this.TitleTextEdit.StyleController = this.dataLayout;
            this.TitleTextEdit.TabIndex = 5;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Size = new System.Drawing.Size(500, 396);
            this.layoutControlGroup1.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.ItemForFirstName,
            this.ItemForLastName,
            this.ItemForHomePhone,
            this.ItemForMobilePhone,
            this.ItemForEmail,
            this.ItemForPhoto,
            this.emptySpaceItem1,
            this.ItemForAddress,
            this.ItemForCity,
            this.emptySpaceItem2,
            this.ItemForFullName,
            this.ItemForBirthDate,
            this.ItemForState,
            this.ItemForZipCode,
            this.emptySpaceItem5,
            this.ItemForDepartment,
            this.ItemForHireDate,
            this.emptySpaceItem4,
            this.ItemForTitle,
            this.ItemForPrefix,
            this.ItemForStatus});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(490, 386);
            // 
            // ItemForFirstName
            // 
            this.ItemForFirstName.Control = this.FirstNameTextEdit;
            this.ItemForFirstName.CustomizationFormText = "First Name";
            this.ItemForFirstName.Location = new System.Drawing.Point(0, 0);
            this.ItemForFirstName.Name = "ItemForFirstName";
            this.ItemForFirstName.Size = new System.Drawing.Size(343, 22);
            this.ItemForFirstName.Text = "First Name";
            this.ItemForFirstName.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForLastName
            // 
            this.ItemForLastName.Control = this.LastNameTextEdit;
            this.ItemForLastName.CustomizationFormText = "Last Name";
            this.ItemForLastName.Location = new System.Drawing.Point(0, 22);
            this.ItemForLastName.Name = "ItemForLastName";
            this.ItemForLastName.Size = new System.Drawing.Size(343, 22);
            this.ItemForLastName.Text = "Last Name";
            this.ItemForLastName.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForHomePhone
            // 
            this.ItemForHomePhone.Control = this.HomePhoneTextEdit;
            this.ItemForHomePhone.CustomizationFormText = "Home Phone";
            this.ItemForHomePhone.Location = new System.Drawing.Point(0, 174);
            this.ItemForHomePhone.Name = "ItemForHomePhone";
            this.ItemForHomePhone.Size = new System.Drawing.Size(490, 22);
            this.ItemForHomePhone.Text = "Home Phone";
            this.ItemForHomePhone.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForMobilePhone
            // 
            this.ItemForMobilePhone.Control = this.MobilePhoneTextEdit;
            this.ItemForMobilePhone.CustomizationFormText = "Mobile Phone";
            this.ItemForMobilePhone.Location = new System.Drawing.Point(0, 196);
            this.ItemForMobilePhone.Name = "ItemForMobilePhone";
            this.ItemForMobilePhone.Size = new System.Drawing.Size(490, 22);
            this.ItemForMobilePhone.Text = "Mobile Phone";
            this.ItemForMobilePhone.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForEmail
            // 
            this.ItemForEmail.Control = this.EmailTextEdit;
            this.ItemForEmail.CustomizationFormText = "Email";
            this.ItemForEmail.Location = new System.Drawing.Point(0, 218);
            this.ItemForEmail.Name = "ItemForEmail";
            this.ItemForEmail.Size = new System.Drawing.Size(490, 22);
            this.ItemForEmail.Text = "Email";
            this.ItemForEmail.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForPhoto
            // 
            this.ItemForPhoto.Control = this.PhotoPictureEdit;
            this.ItemForPhoto.CustomizationFormText = "Photo";
            this.ItemForPhoto.Location = new System.Drawing.Point(343, 0);
            this.ItemForPhoto.Name = "ItemForPhoto";
            this.ItemForPhoto.Padding = new DevExpress.XtraLayout.Utils.Padding(20, 2, 2, 2);
            this.ItemForPhoto.Size = new System.Drawing.Size(147, 88);
            this.ItemForPhoto.Text = "Photo:";
            this.ItemForPhoto.TextSize = new System.Drawing.Size(0, 0);
            this.ItemForPhoto.TextVisible = false;
            // 
            // emptySpaceItem1
            // 
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            this.emptySpaceItem1.Location = new System.Drawing.Point(0, 88);
            this.emptySpaceItem1.MaxSize = new System.Drawing.Size(0, 20);
            this.emptySpaceItem1.MinSize = new System.Drawing.Size(10, 20);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(490, 20);
            this.emptySpaceItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            // 
            // ItemForAddress
            // 
            this.ItemForAddress.Control = this.AddressTextEdit;
            this.ItemForAddress.CustomizationFormText = "Address";
            this.ItemForAddress.Location = new System.Drawing.Point(0, 108);
            this.ItemForAddress.Name = "ItemForAddress";
            this.ItemForAddress.Size = new System.Drawing.Size(490, 22);
            this.ItemForAddress.Text = "Address";
            this.ItemForAddress.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForCity
            // 
            this.ItemForCity.Control = this.CityTextEdit;
            this.ItemForCity.CustomizationFormText = "City";
            this.ItemForCity.Location = new System.Drawing.Point(0, 130);
            this.ItemForCity.Name = "ItemForCity";
            this.ItemForCity.Size = new System.Drawing.Size(195, 24);
            this.ItemForCity.Text = "City";
            this.ItemForCity.TextSize = new System.Drawing.Size(63, 13);
            // 
            // emptySpaceItem2
            // 
            this.emptySpaceItem2.AllowHotTrack = false;
            this.emptySpaceItem2.CustomizationFormText = "emptySpaceItem2";
            this.emptySpaceItem2.Location = new System.Drawing.Point(0, 154);
            this.emptySpaceItem2.MaxSize = new System.Drawing.Size(0, 20);
            this.emptySpaceItem2.MinSize = new System.Drawing.Size(10, 20);
            this.emptySpaceItem2.Name = "emptySpaceItem2";
            this.emptySpaceItem2.Size = new System.Drawing.Size(490, 20);
            this.emptySpaceItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem2.TextSize = new System.Drawing.Size(0, 0);
            // 
            // ItemForFullName
            // 
            this.ItemForFullName.Control = this.FullNameTextEdit;
            this.ItemForFullName.CustomizationFormText = "Full Name";
            this.ItemForFullName.Location = new System.Drawing.Point(0, 44);
            this.ItemForFullName.Name = "ItemForFullName";
            this.ItemForFullName.Size = new System.Drawing.Size(343, 22);
            this.ItemForFullName.Text = "Full Name";
            this.ItemForFullName.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForBirthDate
            // 
            this.ItemForBirthDate.Control = this.BirthDateDateEdit;
            this.ItemForBirthDate.CustomizationFormText = "Birth Date";
            this.ItemForBirthDate.Location = new System.Drawing.Point(0, 66);
            this.ItemForBirthDate.Name = "ItemForBirthDate";
            this.ItemForBirthDate.Size = new System.Drawing.Size(343, 22);
            this.ItemForBirthDate.Text = "Birth Date";
            this.ItemForBirthDate.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForState
            // 
            this.ItemForState.Control = this.StateImageComboBoxEdit;
            this.ItemForState.CustomizationFormText = "State";
            this.ItemForState.Location = new System.Drawing.Point(195, 130);
            this.ItemForState.Name = "ItemForState";
            this.ItemForState.Padding = new DevExpress.XtraLayout.Utils.Padding(20, 2, 2, 2);
            this.ItemForState.Size = new System.Drawing.Size(148, 24);
            this.ItemForState.Text = "State";
            this.ItemForState.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.AutoSize;
            this.ItemForState.TextSize = new System.Drawing.Size(26, 13);
            this.ItemForState.TextToControlDistance = 5;
            // 
            // ItemForZipCode
            // 
            this.ItemForZipCode.Control = this.ZipCodeTextEdit;
            this.ItemForZipCode.CustomizationFormText = "ZipCode";
            this.ItemForZipCode.Location = new System.Drawing.Point(343, 130);
            this.ItemForZipCode.Name = "ItemForZipCode";
            this.ItemForZipCode.Padding = new DevExpress.XtraLayout.Utils.Padding(20, 2, 2, 2);
            this.ItemForZipCode.Size = new System.Drawing.Size(147, 24);
            this.ItemForZipCode.Text = "ZIP code";
            this.ItemForZipCode.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.CustomSize;
            this.ItemForZipCode.TextSize = new System.Drawing.Size(42, 13);
            this.ItemForZipCode.TextToControlDistance = 5;
            // 
            // emptySpaceItem5
            // 
            this.emptySpaceItem5.AllowHotTrack = false;
            this.emptySpaceItem5.CustomizationFormText = "emptySpaceItem5";
            this.emptySpaceItem5.Location = new System.Drawing.Point(0, 240);
            this.emptySpaceItem5.MaxSize = new System.Drawing.Size(0, 20);
            this.emptySpaceItem5.MinSize = new System.Drawing.Size(10, 20);
            this.emptySpaceItem5.Name = "emptySpaceItem5";
            this.emptySpaceItem5.Size = new System.Drawing.Size(490, 20);
            this.emptySpaceItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem5.TextSize = new System.Drawing.Size(0, 0);
            // 
            // ItemForDepartment
            // 
            this.ItemForDepartment.Control = this.DepartmentImageComboBoxEdit;
            this.ItemForDepartment.CustomizationFormText = "Department";
            this.ItemForDepartment.Location = new System.Drawing.Point(0, 284);
            this.ItemForDepartment.Name = "ItemForDepartment";
            this.ItemForDepartment.Size = new System.Drawing.Size(490, 22);
            this.ItemForDepartment.Text = "Department";
            this.ItemForDepartment.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForHireDate
            // 
            this.ItemForHireDate.Control = this.HireDateDateEdit;
            this.ItemForHireDate.CustomizationFormText = "Hire Date";
            this.ItemForHireDate.Location = new System.Drawing.Point(0, 306);
            this.ItemForHireDate.Name = "ItemForHireDate";
            this.ItemForHireDate.Size = new System.Drawing.Size(343, 24);
            this.ItemForHireDate.Text = "Hire Date";
            this.ItemForHireDate.TextSize = new System.Drawing.Size(63, 13);
            // 
            // emptySpaceItem4
            // 
            this.emptySpaceItem4.AllowHotTrack = false;
            this.emptySpaceItem4.CustomizationFormText = "emptySpaceItem4";
            this.emptySpaceItem4.Location = new System.Drawing.Point(0, 330);
            this.emptySpaceItem4.MaxSize = new System.Drawing.Size(20, 0);
            this.emptySpaceItem4.MinSize = new System.Drawing.Size(20, 10);
            this.emptySpaceItem4.Name = "emptySpaceItem4";
            this.emptySpaceItem4.Size = new System.Drawing.Size(490, 56);
            this.emptySpaceItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem4.TextSize = new System.Drawing.Size(0, 0);
            // 
            // ItemForTitle
            // 
            this.ItemForTitle.Control = this.TitleTextEdit;
            this.ItemForTitle.CustomizationFormText = "Title";
            this.ItemForTitle.Location = new System.Drawing.Point(0, 260);
            this.ItemForTitle.Name = "ItemForTitle";
            this.ItemForTitle.Size = new System.Drawing.Size(343, 24);
            this.ItemForTitle.Text = "Title";
            this.ItemForTitle.TextSize = new System.Drawing.Size(63, 13);
            // 
            // ItemForPrefix
            // 
            this.ItemForPrefix.Control = this.PrefixImageComboBoxEdit;
            this.ItemForPrefix.CustomizationFormText = "Prefix";
            this.ItemForPrefix.Location = new System.Drawing.Point(343, 260);
            this.ItemForPrefix.Name = "ItemForPrefix";
            this.ItemForPrefix.Padding = new DevExpress.XtraLayout.Utils.Padding(20, 2, 2, 2);
            this.ItemForPrefix.Size = new System.Drawing.Size(147, 24);
            this.ItemForPrefix.Text = "Prefix";
            this.ItemForPrefix.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.CustomSize;
            this.ItemForPrefix.TextSize = new System.Drawing.Size(42, 13);
            this.ItemForPrefix.TextToControlDistance = 5;
            // 
            // ItemForStatus
            // 
            this.ItemForStatus.Control = this.StatusImageComboBoxEdit;
            this.ItemForStatus.CustomizationFormText = "Status";
            this.ItemForStatus.Location = new System.Drawing.Point(343, 306);
            this.ItemForStatus.Name = "ItemForStatus";
            this.ItemForStatus.Padding = new DevExpress.XtraLayout.Utils.Padding(20, 2, 2, 2);
            this.ItemForStatus.Size = new System.Drawing.Size(147, 24);
            this.ItemForStatus.Text = "Status";
            this.ItemForStatus.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.CustomSize;
            this.ItemForStatus.TextSize = new System.Drawing.Size(42, 13);
            this.ItemForStatus.TextToControlDistance = 5;
            // 
            // barManager
            // 
            this.barManager.Bars.AddRange(new DevExpress.XtraBars.Bar[] {
            this.actionsBar});
            this.barManager.DockControls.Add(this.barDockControlTop);
            this.barManager.DockControls.Add(this.barDockControlBottom);
            this.barManager.DockControls.Add(this.barDockControlLeft);
            this.barManager.DockControls.Add(this.barDockControlRight);
            this.barManager.Form = this;
            this.barManager.Images = this.actionImages;
            this.barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.bbiSave,
            this.bbiClearEditors,
            this.bbiResetChanges});
            this.barManager.MainMenu = this.actionsBar;
            this.barManager.MaxItemId = 3;
            // 
            // actionsBar
            // 
            this.actionsBar.BarName = "Actions";
            this.actionsBar.DockCol = 0;
            this.actionsBar.DockRow = 0;
            this.actionsBar.DockStyle = DevExpress.XtraBars.BarDockStyle.Top;
            this.actionsBar.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
            new DevExpress.XtraBars.LinkPersistInfo(this.bbiSave),
            new DevExpress.XtraBars.LinkPersistInfo(this.bbiClearEditors),
            new DevExpress.XtraBars.LinkPersistInfo(this.bbiResetChanges)});
            this.actionsBar.OptionsBar.AllowQuickCustomization = false;
            this.actionsBar.OptionsBar.DisableCustomization = true;
            this.actionsBar.OptionsBar.DrawDragBorder = false;
            this.actionsBar.OptionsBar.MultiLine = true;
            this.actionsBar.OptionsBar.UseWholeRow = true;
            this.actionsBar.Text = "Actions";
            // 
            // bbiSave
            // 
            this.bbiSave.Caption = "Save Changes";
            this.bbiSave.Id = 0;
            this.bbiSave.ImageOptions.ImageIndex = 0;
            this.bbiSave.Name = "bbiSave";
            this.bbiSave.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            this.bbiSave.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.OnSave);
            // 
            // bbiClearEditors
            // 
            this.bbiClearEditors.Caption = "Clear All";
            this.bbiClearEditors.Id = 1;
            this.bbiClearEditors.ImageOptions.ImageIndex = 2;
            this.bbiClearEditors.Name = "bbiClearEditors";
            this.bbiClearEditors.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            this.bbiClearEditors.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.OnClearEditors);
            // 
            // bbiResetChanges
            // 
            this.bbiResetChanges.Caption = "Reset Changes";
            this.bbiResetChanges.Id = 2;
            this.bbiResetChanges.ImageOptions.ImageIndex = 1;
            this.bbiResetChanges.Name = "bbiResetChanges";
            this.bbiResetChanges.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            this.bbiResetChanges.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.OnResetChanges);
            // 
            // barDockControlTop
            // 
            this.barDockControlTop.CausesValidation = false;
            this.barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.barDockControlTop.Location = new System.Drawing.Point(0, 0);
            this.barDockControlTop.Manager = this.barManager;
            this.barDockControlTop.Size = new System.Drawing.Size(500, 24);
            // 
            // barDockControlBottom
            // 
            this.barDockControlBottom.CausesValidation = false;
            this.barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.barDockControlBottom.Location = new System.Drawing.Point(0, 420);
            this.barDockControlBottom.Manager = this.barManager;
            this.barDockControlBottom.Size = new System.Drawing.Size(500, 0);
            // 
            // barDockControlLeft
            // 
            this.barDockControlLeft.CausesValidation = false;
            this.barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.barDockControlLeft.Location = new System.Drawing.Point(0, 24);
            this.barDockControlLeft.Manager = this.barManager;
            this.barDockControlLeft.Size = new System.Drawing.Size(0, 396);
            // 
            // barDockControlRight
            // 
            this.barDockControlRight.CausesValidation = false;
            this.barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right;
            this.barDockControlRight.Location = new System.Drawing.Point(500, 24);
            this.barDockControlRight.Manager = this.barManager;
            this.barDockControlRight.Size = new System.Drawing.Size(0, 396);
            // 
            // actionImages
            // 
            this.actionImages.Add("save", "image://svgimages/save/save.svg");
            this.actionImages.Add("refresh", "image://svgimages/icon builder/actions_refresh.svg");
            this.actionImages.Add("clearall", "image://svgimages/spreadsheet/clearall.svg");
            // 
            // EmployeeDetailsSimple
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.Controls.Add(this.dataLayout);
            this.Controls.Add(this.barDockControlLeft);
            this.Controls.Add(this.barDockControlRight);
            this.Controls.Add(this.barDockControlBottom);
            this.Controls.Add(this.barDockControlTop);
            this.Name = "EmployeeDetailsSimple";
            this.Size = new System.Drawing.Size(500, 420);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayout)).EndInit();
            this.dataLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.FirstNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.LastNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PrefixImageComboBoxEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DepartmentImageComboBoxEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.StatusImageComboBoxEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HomePhoneTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.MobilePhoneTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EmailTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PhotoPictureEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AddressTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CityTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.StateImageComboBoxEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ZipCodeTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.FullNameTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HireDateDateEdit.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.HireDateDateEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.BirthDateDateEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TitleTextEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFirstName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForLastName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForHomePhone)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForMobilePhone)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForEmail)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForPhoto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForCity)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForFullName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForBirthDate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForState)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForZipCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForDepartment)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForHireDate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForTitle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForPrefix)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForStatus)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.actionImages)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayout;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.TextEdit FirstNameTextEdit;
        private DevExpress.XtraEditors.TextEdit LastNameTextEdit;
        private DevExpress.XtraEditors.ImageComboBoxEdit PrefixImageComboBoxEdit;
        private DevExpress.XtraEditors.ImageComboBoxEdit DepartmentImageComboBoxEdit;
        private DevExpress.XtraEditors.ImageComboBoxEdit StatusImageComboBoxEdit;
        private DevExpress.XtraEditors.PictureEdit PhotoPictureEdit;
        private DevExpress.XtraEditors.TextEdit AddressTextEdit;
        private DevExpress.XtraEditors.TextEdit CityTextEdit;
        private DevExpress.XtraEditors.ImageComboBoxEdit StateImageComboBoxEdit;
        private DevExpress.XtraEditors.TextEdit ZipCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit FullNameTextEdit;
        private DevExpress.XtraEditors.DateEdit HireDateDateEdit;
        private DevExpress.XtraEditors.DateEdit BirthDateDateEdit;
        private DevExpress.XtraEditors.TextEdit TitleTextEdit;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlItem ItemForFirstName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForLastName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDepartment;
        private DevExpress.XtraLayout.LayoutControlItem ItemForHomePhone;
        private DevExpress.XtraLayout.LayoutControlItem ItemForMobilePhone;
        private DevExpress.XtraLayout.LayoutControlItem ItemForEmail;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPhoto;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraLayout.LayoutControlItem ItemForAddress;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCity;
        private DevExpress.XtraLayout.LayoutControlItem ItemForState;
        private DevExpress.XtraLayout.LayoutControlItem ItemForZipCode;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem2;
        private DevExpress.XtraLayout.LayoutControlItem ItemForFullName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForHireDate;
        private DevExpress.XtraLayout.LayoutControlItem ItemForBirthDate;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem4;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem5;
        private DevExpress.XtraLayout.LayoutControlItem ItemForTitle;
        private System.Windows.Forms.BindingSource employeeBindingSource;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPrefix;
        private DevExpress.XtraLayout.LayoutControlItem ItemForStatus;
        private XtraEditors.ButtonEdit HomePhoneTextEdit;
        private XtraEditors.ButtonEdit MobilePhoneTextEdit;
        private XtraEditors.ButtonEdit EmailTextEdit;
        private Utils.SvgImageCollection actionImages;
        private XtraBars.BarManager barManager;
        private XtraBars.BarButtonItem bbiSave;
        private XtraBars.BarButtonItem bbiClearEditors;
        private XtraBars.BarButtonItem bbiResetChanges;
        private XtraBars.Bar actionsBar;
        private XtraBars.BarDockControl barDockControlTop;
        private XtraBars.BarDockControl barDockControlBottom;
        private XtraBars.BarDockControl barDockControlLeft;
        private XtraBars.BarDockControl barDockControlRight;
    }
}
