//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagament.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_History
    {
        public long ID { get; set; }
        public long ID_user { get; set; }
        public string Info_login { get; set; }
    
        public virtual User_List User_List { get; set; }
    }
}
